# Generated by Django 4.2.13 on 2024-10-18 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileManage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"verbose_name": "文件管理", "verbose_name_plural": "文件管理",},
        ),
        migrations.CreateModel(
            name="Directory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("path", models.TextField()),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="directories", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={"verbose_name": "目录", "verbose_name_plural": "目录",},
        ),
    ]
