# Generated by Django 4.2.13 on 2024-12-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index_change", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradioProxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "gradio-chatbot",
                "verbose_name_plural": "gradio-chatbot",
                "managed": False,
            },
        ),
    ]
