# Generated by Django 4.2.13 on 2024-11-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemInfoLive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=50, verbose_name="品牌名称")),
                ("activity_name", models.CharField(max_length=50, verbose_name="活动名称")),
                (
                    "commodity_desc",
                    models.CharField(max_length=200, verbose_name="商品标题"),
                ),
                (
                    "commodity_style_no",
                    models.CharField(max_length=50, verbose_name="商品款号"),
                ),
                ("commodity_no", models.CharField(max_length=50, verbose_name="商品货号")),
                ("item_id", models.CharField(max_length=20, verbose_name="商品ID")),
                ("live_start_time", models.DateTimeField(verbose_name="直播开始时间")),
                ("live_end_time", models.DateTimeField(verbose_name="直播结束时间")),
                ("anchor", models.CharField(max_length=50, verbose_name="主播")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "直播商品信息配置表",
                "verbose_name_plural": "直播商品信息配置表",
                "ordering": ["-create_time"],
                "unique_together": {("item_id", "live_start_time", "live_end_time")},
            },
        ),
    ]
