# Generated by Django 4.2.13 on 2024-11-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_refund_monitor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutputRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"verbose_name": "输出直播报告", "verbose_name_plural": "输出直播报告",},
        ),
        migrations.AlterField(
            model_name="iteminfolive",
            name="brand_name",
            field=models.CharField(max_length=50, verbose_name="品牌"),
        ),
        migrations.AlterField(
            model_name="iteminfolive",
            name="commodity_desc",
            field=models.CharField(max_length=200, verbose_name="商品描述"),
        ),
        migrations.AlterField(
            model_name="iteminfolive",
            name="commodity_no",
            field=models.CharField(max_length=50, verbose_name="系统货号"),
        ),
        migrations.AlterField(
            model_name="iteminfolive",
            name="commodity_style_no",
            field=models.CharField(max_length=50, verbose_name="系统款号"),
        ),
        migrations.AlterField(
            model_name="iteminfolive",
            name="item_id",
            field=models.CharField(max_length=20, verbose_name="外部商品ID"),
        ),
    ]
