# Generated by Django 4.2.13 on 2024-11-28 13:42

import django.contrib.admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessTimeOutLogs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("re_time", models.CharField(max_length=32, verbose_name="请求时间")),
                ("re_user", models.CharField(max_length=32, verbose_name="操作人")),
                ("re_ip", models.CharField(max_length=32, verbose_name="请求IP")),
                ("re_url", models.CharField(max_length=255, verbose_name="请求url")),
                ("re_method", models.CharField(max_length=11, verbose_name="请求方法")),
                ("re_content", models.TextField(null=True, verbose_name="请求参数")),
                ("rp_content", models.TextField(null=True, verbose_name="响应参数")),
                ("access_time", models.IntegerField(verbose_name="响应耗时/ms")),
            ],
            options={"db_table": "access_timeout_logs",},
        ),
        migrations.CreateModel(
            name="OpLogs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("re_time", models.CharField(max_length=32, verbose_name="请求时间")),
                ("re_user", models.CharField(max_length=32, verbose_name="操作人")),
                ("re_ip", models.CharField(max_length=32, verbose_name="请求IP")),
                ("re_url", models.CharField(max_length=255, verbose_name="请求url")),
                ("re_method", models.CharField(max_length=11, verbose_name="请求方法")),
                ("re_content", models.TextField(null=True, verbose_name="请求参数")),
                ("rp_content", models.TextField(null=True, verbose_name="响应参数")),
                ("access_time", models.IntegerField(verbose_name="响应耗时/ms")),
            ],
            options={"db_table": "op_logs",},
        ),
        migrations.CreateModel(
            name="AdminUserLog",
            fields=[],
            options={
                "verbose_name": "表行级操作日志",
                "verbose_name_plural": "表行级操作日志",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin.logentry",),
            managers=[("objects", django.contrib.admin.models.LogEntryManager()),],
        ),
    ]
