# Generated by Django 4.2.13 on 2024-11-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("middlewares", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accesstimeoutlogs",
            options={"verbose_name": "访问超时日志", "verbose_name_plural": "访问超时日志"},
        ),
        migrations.AlterModelOptions(
            name="oplogs",
            options={"verbose_name": "访问日志", "verbose_name_plural": "访问日志"},
        ),
    ]
