# Generated by Django 4.2.13 on 2024-11-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("middlewares", "0002_alter_accesstimeoutlogs_options_alter_oplogs_options"),
    ]

    operations = [
        migrations.RenameModel(old_name="OpLogs", new_name="OutputLogs",),
    ]
