# Generated by Django 4.2.13 on 2024-11-25 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoverImageTemplate",
            fields=[
                (
                    "template_page_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="模板页id",
                    ),
                ),
                (
                    "image_path",
                    models.ImageField(
                        upload_to="industry_report_upload/image/", verbose_name="封面图模板"
                    ),
                ),
                ("title_x", models.IntegerField(default=0, verbose_name="标题x坐标")),
                ("title_y", models.IntegerField(default=0, verbose_name="标题y坐标")),
                (
                    "title_font_size",
                    models.IntegerField(default=60, verbose_name="标题字体大小"),
                ),
                (
                    "title_font_color",
                    models.CharField(
                        default="#000000", max_length=20, verbose_name="标题字体颜色"
                    ),
                ),
                ("date_x", models.IntegerField(default=0, verbose_name="日期x坐标")),
                ("date_y", models.IntegerField(default=0, verbose_name="日期y坐标")),
                (
                    "date_font_size",
                    models.IntegerField(default=120, verbose_name="日期字体大小"),
                ),
                (
                    "date_font_color",
                    models.CharField(
                        default="#000000", max_length=20, verbose_name="日期字体颜色"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={"verbose_name": "报告封面图模板", "verbose_name_plural": "报告封面图模板",},
        ),
        migrations.CreateModel(
            name="UploadFileTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dir_path", models.CharField(max_length=300, verbose_name="待上传目录")),
                ("title", models.CharField(max_length=50, verbose_name="模板标题")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("special", "专题报告"),
                            ("temp", "临时报告"),
                            ("daily", "日报"),
                            ("weekly", "周报"),
                            ("monthly", "月报"),
                            ("yearly", "年报"),
                        ],
                        max_length=50,
                        verbose_name="报告类型",
                    ),
                ),
                (
                    "report_tag",
                    models.CharField(
                        choices=[
                            ("trade", "行业分析"),
                            ("trend", "潮流趋势"),
                            ("style", "款式分析"),
                            ("brand", "品牌分析"),
                            ("store", "店铺分析"),
                            ("goods", "货品分析"),
                            ("promotion", "大促分析"),
                            ("comment", "评论分析"),
                            ("mall", "商场分析"),
                            ("damai_op", "大麦运营"),
                            ("other", "其他"),
                        ],
                        max_length=50,
                        verbose_name="报告标签",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("5fdba8f8c2c411e79346b8ee653d98c5", "天猫"),
                            ("956000afc2cb11e79346b8ee653d98c5", "京东"),
                            ("41f0e16416cd11ec8c41506b4b386376", "抖音"),
                            ("e3d68801c2c911e79346b8ee653d98c5", "唯品会"),
                            ("5fdba878c2c411e79346b8ee653d98c5", "其他"),
                        ],
                        max_length=50,
                        verbose_name="平台",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("BL", "百丽"),
                            ("TT", "他她"),
                            ("BS", "百思图"),
                            ("TM", "天美意"),
                            ("SD", "森达"),
                            ("BT", "拔佳"),
                            ("ST", "思加图"),
                            ("ML", "妙丽"),
                            ("JP", "真美诗"),
                            ("HP", "暇步士"),
                            ("CL", "其乐"),
                            ("SK", "圣伽步"),
                            ("FM", "十五分钟"),
                            ("CM", "冠军（鞋）"),
                            ("XM", "TooManyShoes"),
                            ("QS", "高跟73小时"),
                            ("~", "空"),
                        ],
                        default="~",
                        max_length=50,
                        verbose_name="品牌",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("1565275157315284993", "商业分析用户"),
                            ("1566727058562244610", "【深圳分区】商场客流报告用户"),
                            ("1575361116640366593", "抖音渠道报告推送人群"),
                            ("1584825600115200001", "行业数据推送用户"),
                            ("1639217999669731329", "客流报告-全国日周报（鞋+服）"),
                            ("1649316652629442561", "客流报告-全国日周报（鞋）"),
                            ("1649318779460337666", "客流报告-全国日周报（服）"),
                            ("1754020533718368258", "华北资讯"),
                            ("1754026096548265986", "华东资讯"),
                            ("1754026797026394114", "鲁豫皖资讯"),
                            ("1754027337067819010", "华南资讯"),
                            ("1754027959678693377", "华中资讯"),
                            ("1754028267209637890", "西北资讯"),
                            ("1754028530490294274", "西南资讯"),
                            ("1754028896631681025", "东北资讯"),
                            ("1857363458212118529", "首条评论报告-用户组"),
                            ("1857363826052198401", "京东爆款监控报告-用户组"),
                            ("1857364245356769282", "京东新风向标数据-用户组"),
                            ("1858340952643674113", "STM分析报告-用户组"),
                            ("1858341036437479425", "潮流款式报告-用户组"),
                            ("1858341116913590273", "全量评论月报-用户组"),
                            ("1858341150627405826", "Champion店铺监控-用户组"),
                            ("1858341259238907906", "百丽男鞋店铺监控-用户组"),
                            ("1858341287181361153", "思加图大盘价格段分析-用户组"),
                            ("1858341317485207553", "女鞋大盘&集团品牌分析-用户组"),
                            ("1858341349026373633", "小红书蒲公英-用户组"),
                            ("1858341377040130049", "服饰电商评论日报-用户组"),
                            ("1858341446384558081", "唯品日报-用户组"),
                            ("1858341473316184066", "直播达人监控-用户组"),
                            ("1858341497622175745", "五大品牌top爆款监控-用户组"),
                            ("1858832557316390914", "数据应用部-测试角色"),
                        ],
                        max_length=50,
                        verbose_name="角色组id",
                    ),
                ),
                (
                    "if_to_wps",
                    models.BooleanField(default=False, verbose_name="是否转为wps"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "template_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="industry_report_upload.coverimagetemplate",
                        verbose_name="模板页id",
                    ),
                ),
            ],
            options={"verbose_name": "待上传文件配置", "verbose_name_plural": "待上传文件配置",},
        ),
    ]
