# Generated by Django 4.2.13 on 2024-11-25 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("industry_report_upload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadfiletemplate",
            name="template_page",
            field=models.ForeignKey(
                default="page-0001",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="industry_report_upload.coverimagetemplate",
                verbose_name="模板页id",
            ),
        ),
    ]
