# Generated by Django 4.2.13 on 2024-11-27 05:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("industry_report_upload", "0003_alter_uploadfiletemplate_brand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadfiletemplate",
            name="brand",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("BL", "百丽"),
                    ("TT", "他她"),
                    ("BS", "百思图"),
                    ("TM", "天美意"),
                    ("SD", "森达"),
                    ("BT", "拔佳"),
                    ("ST", "思加图"),
                    ("ML", "妙丽"),
                    ("JP", "真美诗"),
                    ("HP", "暇步士"),
                    ("CL", "其乐"),
                    ("SK", "圣伽步"),
                    ("FM", "十五分钟"),
                    ("CM", "冠军（鞋）"),
                    ("XM", "TooManyShoes"),
                    ("QS", "高跟73小时"),
                    ("~", "全部"),
                ],
                default="~",
                max_length=300,
                verbose_name="品牌",
            ),
        ),
        migrations.AlterField(
            model_name="uploadfiletemplate",
            name="role",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("1565275157315284993", "商业分析用户"),
                    ("1575361116640366593", "抖音渠道报告推送人群"),
                    ("1584825600115200001", "行业数据推送用户"),
                    ("1857363458212118529", "首条评论报告-用户组"),
                    ("1857363826052198401", "京东爆款监控报告-用户组"),
                    ("1857364245356769282", "京东新风向标数据-用户组"),
                    ("1858340952643674113", "STM分析报告-用户组"),
                    ("1858341036437479425", "潮流款式报告-用户组"),
                    ("1858341116913590273", "全量评论月报-用户组"),
                    ("1858341150627405826", "Champion店铺监控-用户组"),
                    ("1858341259238907906", "百丽男鞋店铺监控-用户组"),
                    ("1858341287181361153", "思加图大盘价格段分析-用户组"),
                    ("1858341317485207553", "女鞋大盘&集团品牌分析-用户组"),
                    ("1858341349026373633", "小红书蒲公英-用户组"),
                    ("1858341377040130049", "服饰电商评论日报-用户组"),
                    ("1858341446384558081", "唯品日报-用户组"),
                    ("1858341473316184066", "直播达人监控-用户组"),
                    ("1858341497622175745", "五大品牌top爆款监控-用户组"),
                    ("1858832557316390914", "数据应用部-测试角色"),
                    ("1861232953867517954", "集团高层角色组"),
                ],
                max_length=50,
                verbose_name="角色组id",
            ),
        ),
    ]
