# Generated by Django 4.2.13 on 2024-11-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_report_upload", "0004_alter_uploadfiletemplate_brand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coverimagetemplate",
            name="date_font_size",
            field=models.IntegerField(default=60, verbose_name="日期字体大小"),
        ),
        migrations.AlterField(
            model_name="coverimagetemplate",
            name="title_font_size",
            field=models.IntegerField(default=120, verbose_name="标题字体大小"),
        ),
    ]
